package com.macrobalance.cart.entity;

import com.macrobalance.common.entity.BaseEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * JPA entity representing a shopping cart.
 *
 * <p>A cart belongs to either an authenticated user or a guest session,
 * never both simultaneously:
 * <ul>
 *   <li>{@code userId} is set for logged-in users</li>
 *   <li>{@code guestId} is set for guest sessions (UUID generated by the frontend)</li>
 * </ul>
 *
 * <p>Cart lifecycle via the {@code status} field:
 * <ul>
 *   <li>{@code ACTIVE} — the current working cart, open for item changes</li>
 *   <li>{@code MERGED} — a guest cart that was merged into a user cart on login</li>
 *   <li>{@code CHECKED_OUT} — a cart that was converted into an order</li>
 * </ul>
 *
 * <p>Extends {@link BaseEntity} for {@code id}, audit timestamps,
 * {@code createdBy}, {@code updatedBy}, and optimistic locking via {@code version}.
 */
@Entity
@Getter
@Setter
@Table(name = "carts")
public class Cart extends BaseEntity {

    /**
     * ID of the authenticated user who owns this cart.
     * Null for guest carts. Populated on login or registration.
     */
    @Column(name = "user_id")
    private Long userId;

    /**
     * UUID identifying a guest session.
     * Generated by the frontend and sent via the {@code X-Guest-Id} header.
     * Null for authenticated user carts.
     */
    @Column(name = "guest_id")
    private String guestId;

    /**
     * Lifecycle status of the cart.
     *
     * <ul>
     *   <li>{@code ACTIVE} — open and available for modifications</li>
     *   <li>{@code MERGED} — guest cart absorbed into a user cart on login</li>
     *   <li>{@code CHECKED_OUT} — converted to an order, no longer modifiable</li>
     * </ul>
     */
    @Column(nullable = false)
    private String status = "ACTIVE";
}